### PR TITLE
Add contribution guide

### PR DESCRIPTION
**Pull request by kfogel**

### CODE REVIEW

**Comment by kfogel** [comment]
Oh, some of our PDC repositories use `.github/`, so this is going to be a more complex conversation now.  Closing this PR.  I'll go over to Zulip and have the conversation.

**Review by bickelj — DISMISSED** [review]

**Comment by bickelj** [comment]
I remembered that I hadn't reviewed this, and then approved the changes before remembering the comment above. I'll revisit.

**Review by bickelj — DISMISSED** [review]
After [further discussion](https://chat.opentechstrategies.com/#narrow/stream/75-PDC/topic/developer.20documentation), at least two developers would be OK with this contribution guide pointing straight to the OTS contribution guide, in addition to the meta repository pointing to the OTS contribution guide. We still need input from others but I, for one, think this change is OK as-is.

**Comment by bickelj** [comment]
I updated the commit in this branch to follow the team agreement that formed a week or two after this PR. It follows the pattern from https://github.com/PhilanthropyDataCommons/front-end/pull/366.

**Review by slifty — APPROVED** [review]

**Pull request merged**
